#!/usr/bin/perl
## Copyright (C) 2017 by Yours Truly

use strict;
use warnings FATAL => 'all';
use Math::Trig;

print "Enter the circumference ray: ";
chomp($radius = <STDIN>);
$circumference = $radius * 2 * pi;
print "The circumference of a circle of radius $radius is $circumference \n";
