#!/usr/bin/perl
## Copyright (C) 2017 by Yours Truly
use strict;
use warnings FATAL => 'all';

use Math::Trig;
my $circumference = 12.5 * 2 * pi;
print "The circumference of a circle of ray 12.5 is $circumference \n";
